poi_dict = {
    "chicken": {"x":0, "y":1,"layer":["Overworld"] },
    "cow": {"x":0, "y":2, "layer":["Overworld"] },
    "mountain_entrance": {"x":-2, "y":6, "layer":["Overworld","Underground"] },
    "ash_tree": {"x":-1, "y":0, "layer":["Overworld"] },
    "forge": {"x":1, "y":5, "layer":["Overworld"] },
    "copper_rocks": {"x":2, "y":0, "layer":["Overworld"] },
    "red_slime": {"x":2, "y":-2, "layer":["Overworld"] },
    "green_slime": {"x":0, "y":-1, "layer":["Overworld"] },
    "yellow_slime": {"x":4, "y":-1, "layer":["Overworld"] },
    "blue_slime": {"x":2, "y":-1, "layer":["Overworld"] },
    "bank": {"x":4, "y":1, "layer":["Overworld"] },
    "gudgeon_spot": {"x":4, "y":2, "layer":["Overworld"] },
    "shrimp_spot": {"x":5, "y":2, "layer":["Overworld"] },

    "woodcutting": {"x":-2, "y":-3, "layer":["Overworld"] },
    "cooking": {"x": 1, "y": 1, "layer": ["Overworld"]},
    "weaponcrafting": {"x": 2, "y": 1, "layer": ["Overworld"]},
    "gearcrafting": {"x": 3, "y": 1, "layer": ["Overworld"]},
    "jewelrycrafting": {"x": 1, "y": 3, "layer": ["Overworld"]},
    "alchemy": {"x": 2, "y": 3, "layer": ["Overworld"]},
    "mining": {"x": 1, "y": 5, "layer": ["Overworld"]},
    "sunflower_field": {"x": 2, "y": 2, "layer": ["Overworld"]},
}