loot_dict = {
    "copper_ore": {"action":"gather","location":"copper_rocks" },
    "feather": {"action":"fight","location":"chicken" },
    "ash_wood": {"action":"gather","location": "ash_tree" },
    "gudgeon": {"action":"gather","location": "gudgeon_spot" },
    "algae": {"action":"gather","location": "gudgeon_spot" },
    "shell": {"action":"gather","location": "gudgeon_spot" },
    "shrimp": {"action":"gather","location": "shrimp_spot" },
    "golden_shrimp": {"action":"gather","location": "shrimp_spot" },
    "red_slimeball": {"action":"fight","location":"red_slime" },
    "green_slimeball": {"action":"fight","location":"green_slime" },
    "yellow_slimeball": {"action":"fight","location":"yellow_slime" },
    "blue_slimeball": {"action":"fight","location":"blue_slime" },
    "sunflower": {"action":"gather","location":"sunflower_field" },
    "wool": {"action":"fight","location":"sheep" },
    "iron_ore": {"action":"gather","location":"iron_rocks"},
    "raw_beef": {"action":"fight","location":"cow"},
    "milk_bucket": {"action":"fight","location":"cow"},
    "cowhide": {"action":"fight","location":"cow"},
}