loot_dict = {
    "copper_ore":           {"action":"gather", "location":"copper_rocks" },
    "feather":              {"action":"fight",  "location":"chicken" },
    "raw_chicken":          {"action":"fight",  "location":"chicken" },
    "ash_wood":             {"action":"gather", "location":"ash_tree" },
    "spruce_wood":          {"action":"gather", "location":"spruce_tree"},
    "gudgeon":              {"action":"gather", "location":"gudgeon_spot" },
    "algae":                {"action":"gather", "location":"gudgeon_spot" },
    "shell":                {"action":"gather", "location":"gudgeon_spot" },
    "shrimp":               {"action":"gather", "location":"shrimp_spot" },
    "golden_shrimp":        {"action":"gather", "location":"shrimp_spot" },
    "red_slimeball":        {"action":"fight",  "location":"red_slime" },
    "green_slimeball":      {"action":"fight",  "location":"green_slime" },
    "yellow_slimeball":     {"action":"fight",  "location":"yellow_slime" },
    "blue_slimeball":       {"action":"fight",  "location":"blue_slime" },
    "sunflower":            {"action":"gather", "location":"sunflower_field" },
    "wool":                 {"action":"fight",  "location":"sheep" },
    "iron_ore":             {"action":"gather", "location":"iron_rocks"},
    "raw_beef":             {"action":"fight",  "location":"cow"},
    "milk_bucket":          {"action":"fight",  "location":"cow"},
    "cowhide":              {"action":"fight",  "location":"cow"},
    "nettle_leaf":          {"action":"gather", "location":"nettle"},
    "trout":                {"action":"gather", "location":"trout_spot"},
    "mushroom":             {"action":"fight",  "location":"mushmush"},
    "forest_ring":          {"action":"fight",  "location":"mushmush"},
    "birch_wood":           {"action":"gather", "location":"birch_tree"},
    "cloth":                {"action":"trade",  "location":"tailor"},
    "hard_leather":         {"action":"trade",  "location":"tailor"},
    "sand_snakeskin":       {"action":"trade",  "location":"tailor"},
    "snakeskin":            {"action":"trade",  "location":"tailor"},
    "burn_rune":            {"action":"trade",  "location":"rune_vendor"},
    "healing_aura_rune":    {"action":"trade",  "location":"rune_vendor"},
    "healing_rune":         {"action":"trade",  "location":"rune_vendor"},
    "lifesteal_rune":       {"action":"trade",  "location":"rune_vendor"},
    "protection_rune":      {"action":"trade",  "location":"rune_vendor"},
    "green_cloth":          {"action":"fight",  "location":"highwayman"},
    "highwayman_dagger":    {"action":"fight",  "location":"highwayman"},
    "raw_wolf_meat":        {"action":"fight",  "location":"wolf"},
    "wolf_bone":            {"action":"fight",  "location":"wolf"},
    "wolf_hair":            {"action":"fight",  "location":"wolf"},
    "wolf_ears":            {"action":"fight",  "location":"wolf"},
    "flying_wing":          {"action":"fight",  "location":"flying_snake"},
    "snake_hide":           {"action":"fight",  "location":"flying_snake"},
    "jasper_crystal":       {"action":"trade",  "location":"tasks_trader"},#chanage to trade once task_trader is available
    "magical_cure":         {"action":"trade",  "location":"tasks_trader"},
    "astralyte_crystal":    {"action":"trade", "location": "tasks_trader"},
    "enchanted_fabric":     {"action":"trade", "location": "tasks_trader"},
    "tasks_coin":           {"action":"task",   "location":"tasks_master"},
    "pig_skin":             {"action":"fight",  "location":"pig" },
    "skeleton_bone":        {"action":"fight",  "location":"skeleton" },
    "skeleton_skull":       {"action":"fight",  "location":"skeleton" },
    "lich_tomb_key":        {"action":"fight",  "location":"skeleton" },
    "ogre_eye":             {"action":"fight",  "location":"ogre" },
    "ogre_skin":            {"action":"fight",  "location":"ogre" },
    "old_boots":            {"action":"fight",  "location":"spider" },
    "spider_leg":           {"action":"fight",  "location":"spider" },
    "king_slimeball":       {"action":"fight",  "location":"king_slime" },
    "coal":                 {"action":"gather", "location":"coal_rocks"},
    "gold_ore":             {"action":"gather", "location":"gold_rocks"},
    "vampire_blood":        {"action":"fight",  "location":"vampire"},
    "vampire_tooth":        {"action":"fight",  "location":"vampire"},
    "dead_wood":            {"action":"gather", "location":"dead_tree"},
    "cyclops_eye":          {"action":"fight",  "location":"cyclops"},
    "owlbear_hair":         {"action":"fight",  "location":"owlbear"},
    "owlbear_claw":         {"action":"fight",  "location":"owlbear"},
    "corrupted_gem":        {"action":"fight",  "location":"corrupted_owlbear"},
    "demon_horn":           {"action":"fight",  "location":"demon"},
    "piece_of_obsidian":    {"action":"fight",  "location":"demon"},
}