poi_dict = {
    "chicken":              {"x": 0 , "y": 1 , "layer":["overworld"] },
    "cow":                  {"x": 0 , "y": 2 , "layer":["overworld"] },
    "ash_tree":             {"x":-1 , "y": 0 , "layer":["overworld"] },
    "forge":                {"x": 1 , "y": 5 , "layer":["overworld"] },
    "copper_rocks":         {"x": 2 , "y": 0 , "layer":["overworld"] },
    "red_slime":            {"x": 1 , "y":-1 , "layer":["overworld"] },
    "green_slime":          {"x": 0 , "y":-1 , "layer":["overworld"] },
    "yellow_slime":         {"x": 4 , "y":-1 , "layer":["overworld"] },
    "blue_slime":           {"x": 2 , "y":-1 , "layer":["overworld"] },
    "bank":                 {"x": 4 , "y": 1 , "layer":["overworld"] },
    "gudgeon_spot":         {"x": 4 , "y": 2 , "layer":["overworld"] },
    "shrimp_spot":          {"x": 5 , "y": 2 , "layer":["overworld"] },
    "sunflower_field":      {"x": 2 , "y": 2 , "layer":["overworld"] },
    "sheep":                {"x": 5 , "y": 12, "layer":["overworld"] },
    "iron_rocks":           {"x": 1 , "y": 7 , "layer":["overworld"] },
    "spruce_tree":          {"x": 2 , "y": 6 , "layer":["overworld"] },
    "nettle":               {"x": 7 , "y": 14, "layer":["overworld"] },
    "trout_spot":           {"x": 7 , "y": 12, "layer":["overworld"] },
    "mushmush":             {"x": 5 , "y": 3 , "layer":["overworld"] },
    "birch_tree":           {"x": 3 , "y": 5 , "layer":["overworld"] },
    "wolf":                 {"x":-2 , "y": 1 , "layer":["overworld"] },
    "highwayman":           {"x": 2 , "y": 8 , "layer":["overworld"] },
    "flying_snake":         {"x": 5 , "y": 4 , "layer":["overworld"] },
    "skeleton":             {"x": 8 , "y": 6 , "layer":["overworld"] },
    "pig":                  {"x":-3 , "y":-3 , "layer":["overworld"] },
    "ogre":                 {"x": 8 , "y":-2 , "layer":["overworld"] },
    "spider":               {"x":-3 , "y": 12, "layer":["overworld"] },
    "king_slime":           {"x": 3 , "y":-1 , "layer":["overworld"] },
    "coal_rocks":           {"x": 1 , "y": 6 , "layer":["overworld"] },
    "vampire":              {"x": 10, "y": 6 , "layer":["overworld"] },
    "dead_tree":            {"x": 9 , "y": 6 , "layer":["overworld"] },
    "gold_rocks":           {"x": 5 , "y":-4 , "layer":["underground"], "proxy": "mine_nord"},
    "cyclops":              {"x": 7 , "y":-3 , "layer":["overworld"] },
    "mithril_rocks":        {"x":-2 , "y": 5 , "layer":["underground"], "proxy": "mine_ouest"},
    "owlbear":              {"x":10 , "y": 1 , "layer":["overworld"]}, 
    "demon":                {"x": 0 , "y": 0 , "layer":["overworld"]}, #location decided by event
    "corrupted_owlbear":    {"x": 0 , "y": 0 , "layer":["overworld"]}, #location decided by event

    "woodcutting":          {"x":-2 , "y":-3 , "layer":["overworld"] },
    "cooking":              {"x": 1 , "y": 1 , "layer":["overworld"] },
    "weaponcrafting":       {"x": 2 , "y": 1 , "layer":["overworld"] },
    "gearcrafting":         {"x": 3 , "y": 1 , "layer":["overworld"] },
    "jewelrycrafting":      {"x": 1 , "y": 3 , "layer":["overworld"] },
    "alchemy":              {"x": 2 , "y": 3 , "layer":["overworld"] },
    "mining":               {"x": 1 , "y": 5 , "layer":["overworld"] },

    "tailor":               {"x": 3 , "y": 3 , "layer":["overworld"] },
    "rune_vendor":          {"x": 8 , "y": 13, "layer":["overworld"] },
    "cultist_wizard":       {"x": 2 , "y": 13, "layer":["overworld"] },

    "tasks_master_monster": {"x": 1 , "y": 2 , "layer":["overworld"] },
    "tasks_master_item":    {"x": 4 , "y": 13, "layer":["overworld"] },
    "tasks_trader":         {"x": 5 , "y": 11, "layer":["overworld"] },

    "mine_nord":            {"x": 5 , "y":-3 , "layer":["underground", "overworld"], "proxy": "mine_nord"},
    "mine_ouest":           {"x":-2 , "y": 6 , "layer":["underground", "overworld"], "proxy": "mine_ouest"},
    "spider_house":         {"x":-3 , "y": 12, "layer":["interior", "overworld"], "proxy": "spider_house"},

    "void":                 {"x":-10, "y":-10, "layer":["overworld"], "proxy": None},

}