poi_dict = {
    "chicken": {"x":0, "y":1,"layer":["overworld"] },
    "cow": {"x":0, "y":2, "layer":["overworld"] },
    "mountain_entrance": {"x":-2, "y":6, "layer":["overworld","underground"] },
    "ash_tree": {"x":-1, "y":0, "layer":["overworld"] },
    "forge": {"x":1, "y":5, "layer":["overworld"] },
    "copper_rocks": {"x":2, "y":0, "layer":["overworld"] },
    "red_slime": {"x":2, "y":-2, "layer":["overworld"] },
    "green_slime": {"x":0, "y":-1, "layer":["overworld"] },
    "yellow_slime": {"x":4, "y":-1, "layer":["overworld"] },
    "blue_slime": {"x":2, "y":-1, "layer":["overworld"] },
    "bank": {"x":4, "y":1, "layer":["overworld"] },
    "gudgeon_spot": {"x":4, "y":2, "layer":["overworld"] },
    "shrimp_spot": {"x":5, "y":2, "layer":["overworld"] },
    "sunflower_field": {"x": 2, "y": 2, "layer": ["overworld"]},
    "sheep": {"x":5, "y":12, "layer":["overworld"] },
    "iron_rocks": {"x":1, "y":7, "layer":["overworld"] },
    "spruce_tree": {"x":2, "y":6, "layer":["overworld"] },
    "nettle": {"x":7, "y":14, "layer":["overworld"] },
    "trout_spot": {"x":7, "y":12, "layer":["overworld"] },
    "mushmush": {"x":5, "y":3, "layer":["overworld"] },
    "birch_tree": {"x":3, "y":5, "layer":["overworld"] },

    "woodcutting": {"x":-2, "y":-3, "layer":["overworld"] },
    "cooking": {"x": 1, "y": 1, "layer": ["overworld"]},
    "weaponcrafting": {"x": 2, "y": 1, "layer": ["overworld"]},
    "gearcrafting": {"x": 3, "y": 1, "layer": ["overworld"]},
    "jewelrycrafting": {"x": 1, "y": 3, "layer": ["overworld"]},
    "alchemy": {"x": 2, "y": 3, "layer": ["overworld"]},
    "mining": {"x": 1, "y": 5, "layer": ["overworld"]}
}